// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromotionApi.Models;

#nullable disable

namespace PromotionApi.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    partial class PromotionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PromotionApi.Models.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Condition")
                        .HasColumnType("double");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = "fb063534-11fe-40a5-ae59-ecc53bbc6eb7",
                            Code = "SUMMER2023",
                            Condition = 850000.0,
                            DateExpire = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 15f,
                            MerchantId = "2236b29d-c850-4c6e-bb29-629be5eace69",
                            QuantityAvailable = 40
                        },
                        new
                        {
                            Id = "634f7816-e921-4873-b7d6-d583c717ded0",
                            Code = "FALLSALE2023",
                            Condition = 750000.0,
                            DateExpire = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 20f,
                            MerchantId = "2236b29d-c850-4c6e-bb29-629be5eace69",
                            QuantityAvailable = 400
                        },
                        new
                        {
                            Id = "07965e75-5e8e-498f-ad3e-91ab366bbb3a",
                            Code = "HOLIDAY2023",
                            Condition = 950000.0,
                            DateExpire = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 25f,
                            MerchantId = "2236b29d-c850-4c6e-bb29-629be5eace69",
                            QuantityAvailable = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
